### ISSUE TITLE
Registration: Frontend [Users]

### ISSUE THREAD

**Issue by oryanmoshe** [DataHackIL/ninjathon#25]
### Why
Our registration flow requires a sign up screen.
All users who want to register will use this screen for the purpose.
### Requirements
This screen should be coded using React (in TypeScript), and contain:
- [ ] Email (text) - mandatory field - _must be a valid email address_
- [ ] Password (text) - mandatory field - _at least 8 chars long and contain lower, upper and numbers_
- [ ] First Name (text) - mandatory field
- [ ] Last Name (text) - mandatory field
- [ ] Area of expertise (multi-choice combobox) - mandatory field
- [ ] Resume (file) - optional field

For UI we'll use the [material-ui](https://material-ui.com/) package.
All validation tests should happen on both the client side and the backend.

**Comment by shakedlokits** [comment]
1. There are multiple fields that we [had on the previous system](https://github.com/DataHackIL/datahack_registration/blob/master/app/models/user.server.model.js) wanna go through them together on the phone and see if some of them are still relevant?
2. About the UI framework, I think we should add a shared resources directory that we will bind a volume to in each container, that way we have a central location to edit our design each year for the entire system, what do you think?
3. I think Area of expertise should probably be optional because it's not "really" required for admin's and staff.
